### ISSUE TITLE
[Bug]: org :pre-build command failed

### ISSUE THREAD

**Issue by sgtlaggy** [progfolio/elpaca#75] opened 2023-03-01 19:18 UTC
### Elpaca Version

Elpaca d871b45 HEAD -> master, origin/master, origin/HEAD
installer:      0.2
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.16.0)
 of 2023-01-17, modified by Debian
git --version:  git version 2.39.1

### Operating System

Kali-Linux (2023.1) through WSL 1 on Windows 11 (22H2 22621.1265)

### Bug Description

Using obligatory `(setq package-enable-at-startup nil)` in `early-init.el` and minimal `init.el` consisting of only elpaca bootstrap followed by `(elpaca org)`

With the above setup, org fails with `:pre-build command failed`

Through screen recording, I was able to catch _most_ of the error messages during `pre-build`:
`File mode specification error: (error List nesting exceeds 'max-lisp-eval-depth...`
`(let ((load-prefer-newer t) (gc-cons-percentage 1.0)) (require 'elpaca) (norm...`
(screenshots attached in case I mistyped)
![image](https://user-images.githubusercontent.com/8661717/222241297-0965852c-4d11-4057-a46c-080c024fdaad.png)
![image](https://user-images.githubusercontent.com/8661717/222241371-51cc46e9-99c1-48a2-9cfc-b1853fddce76.png)

**Comment by progfolio** [comment] 2023-03-01 19:38
Thanks for the report.
Can you re-run and try to get the entire log?
After the failure, type "s" in the log-buffer followed by "RET".
That should default to the search filter ".*" which will show the entire log.
Then you can type "c" to copy the current view to the clipboard, which can be shared here.

**Comment by sgtlaggy** [comment] 2023-03-01 19:58
<details><summary>Log @2023-03-01 11:55:12 -0800</summary>
search filter: ".*"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>elpaca</td><td>queued</td><td>Package queued</td><td>38.017609</td></tr>
<tr><td>org</td><td>queued</td><td>Package queued</td><td>38.017882</td></tr>
<tr><td>elpaca</td><td>cloning-deps</td><td>Cloning Dependencies</td><td>38.017974</td></tr>
<tr><td>elpaca</td><td>cloning-deps</td><td>No external dependencies detected</td><td>38.018360</td></tr>
<tr><td>elpaca</td><td>linking</td><td>Linking build files</td><td>38.018370</td></tr>
<tr><td>elpaca</td><td>linking</td><td>Build files linked</td><td>38.027712</td></tr>
<tr><td>elpaca</td><td>autoloads</td><td>Generating autoloads: /tmp/elpaca.11EXSB/elpaca/builds/elpaca</td><td>38.030324</td></tr>
<tr><td>org</td><td>cloning</td><td>Cloning</td><td>38.030363</td></tr>
<tr><td>elpaca</td><td>autoloads</td><td>  INFO     Scraping files for elpaca-autoloads.el... </td><td>38.409105</td></tr>
<tr><td>elpaca</td><td>autoloads</td><td>  INFO     Scraping files for elpaca-autoloads.el...done</td><td>38.409112</td></tr>
<tr><td>elpaca</td><td>autoloads</td><td>Autoloads Generated</td><td>38.420112</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Byte compiling</td><td>38.420138</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Checking /tmp/elpaca.11EXSB/elpaca/builds/elpaca...</td><td>38.594284</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-autoloads.el...</td><td>38.616116</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-info.el...</td><td>38.616124</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>In toplevel form:</td><td>38.800274</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>elpaca-info.el:27:1: Warning: defface for ‘elpaca-info-section’ fails to</td><td>38.800289</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>    specify containing group</td><td>38.800299</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>elpaca-info.el:29:1: Warning: defface for ‘elpaca-info-package’ fails to</td><td>38.822833</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>    specify containing group</td><td>38.822856</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-log.el...</td><td>38.822864</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-manager.el...</td><td>38.822871</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-menu-gnu-elpa-mirror.el...</td><td>38.845507</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-menu-melpa.el...</td><td>38.845517</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-menu-non-gnu-elpa.el...</td><td>38.867577</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-menu-org.el...</td><td>38.867586</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-process.el...</td><td>38.867593</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-test.el...</td><td>38.890566</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca-ui.el...</td><td>38.890583</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Compiling /tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca.el...</td><td>38.913386</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Done (Total of 11 files compiled, 1 skipped)</td><td>38.963337</td></tr>
<tr><td>elpaca</td><td>byte-compilation</td><td>Byte compilation complete</td><td>38.997544</td></tr>
<tr><td>elpaca</td><td>info</td><td>Compiling Info files</td><td>38.997578</td></tr>
<tr><td>elpaca</td><td>info</td><td>Info compiled</td><td>39.256548</td></tr>
<tr><td>elpaca</td><td>info</td><td>Installing Info files</td><td>39.256668</td></tr>
<tr><td>elpaca</td><td>info</td><td>/tmp/elpaca.11EXSB/elpaca/builds/elpaca/elpaca.info</td><td>39.256743</td></tr>
<tr><td>elpaca</td><td>info</td><td>Info installed</td><td>39.274628</td></tr>
<tr><td>elpaca</td><td>info</td><td>Adding Info path</td><td>39.274686</td></tr>
<tr><td>elpaca</td><td>finished</td><td>✓ 1.257 secs</td><td>39.274759</td></tr>
<tr><td>org</td><td>cloning</td><td>Resolving deltas: 100% (15644/15644), done.</td><td>55.027187</td></tr>
<tr><td>org</td><td>pre-build</td><td>Running :pre-build commands</td><td>55.403533</td></tr>
<tr><td>org</td><td>pre-build</td><td>Running command: (progn (require 'elpaca-menu-org) (elpaca-menu-org--build))</td><td>55.663637</td></tr>
<tr><td>org</td><td>pre-build</td><td>Org version: 9.6.1 9.6.1-n/a-gaa2249</td><td>56.179294</td></tr>
<tr><td>org</td><td>pre-build</td><td>Loading /tmp/elpaca.11EXSB/elpaca/repos/org/lisp/org-compat.el (source)...</td><td>56.201724</td></tr>
<tr><td>org</td><td>pre-build</td><td>Loading /tmp/elpaca.11EXSB/elpaca/repos/org/mk/org-fixup.el (source)...</td><td>56.240911</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making loaddefs</td><td>56.273696</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making org-version</td><td>57.654029</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making manuals</td><td>57.676397</td></tr>
<tr><td>org</td><td>pre-build</td><td>File mode specification error: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)</td><td>58.454358</td></tr>
<tr><td>org</td><td>pre-build</td><td>Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")</td><td>59.537188</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (derived-mode-p 'org-mode)</td><td>59.537199</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>59.537209</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537226</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537235</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>59.537242</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>59.537251</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>59.537260</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537267</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537275</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>59.537281</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>59.537287</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>59.537294</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537302</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.537309</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>59.537315</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>59.558982</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>59.558990</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.558997</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.559004</td></tr>
<tr><td>org</td><td>pre-build</td><td>...</td><td>59.559009</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>59.559016</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>59.559022</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.559029</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x166fe3ffea9f2bec>) t)</td><td>59.559036</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>59.559041</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p()</td><td>59.559047</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-element-at-point()</td><td>59.559053</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-export-output-file-name(".texi" nil)</td><td>59.559059</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-texinfo-export-to-texinfo()</td><td>59.559064</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (while --dolist-tail-- (setq manual (car --dolist-tail--)) (find-file manual) (org-texinfo-export-to-texinfo) (setq --dolist-tail-- (cdr --dolist-tail--)))</td><td>59.559071</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (let ((--dolist-tail-- '("../doc/org-manual.org" "../doc/org-guide.org")) manual) (while --dolist-tail-- (setq manual (car --dolist-tail--)) (find-file manual) (org-texinfo-export-to-texinfo) (setq --dolist-tail-- (cdr --dolist-tail--))))</td><td>59.559078</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-make-manuals()</td><td>59.559083</td></tr>
<tr><td>org</td><td>pre-build</td><td>  elpaca-menu-org--build()</td><td>59.559089</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (progn (require 'elpaca-menu-org) (elpaca-menu-org--build))</td><td>59.559095</td></tr>
<tr><td>org</td><td>pre-build</td><td>  eval((progn (require 'elpaca-menu-org) (elpaca-menu-org--build)) t)</td><td>59.559100</td></tr>
<tr><td>org</td><td>pre-build</td><td>  elpaca--run-build-commands((progn (require 'elpaca-menu-org) (elpaca-menu-org--build)))</td><td>59.559106</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (let ((load-prefer-newer t) (gc-cons-percentage 1.0)) (require 'elpaca) (normal-top-level-add-subdirs-to-load-path) (elpaca--run-build-commands '(progn (require 'elpaca-menu-org) (elpaca-menu-org--build))))</td><td>59.559558</td></tr>
<tr><td>org</td><td>pre-build</td><td>  command-line-1(("-L" "./" "-L" "/tmp/elpaca.11EXSB/elpaca/builds/elpaca/" "--eval" "(let ((load-prefer-newer t) (gc-cons-percentage 1...."))</td><td>59.559566</td></tr>
<tr><td>org</td><td>pre-build</td><td>  command-line()</td><td>59.559572</td></tr>
<tr><td>org</td><td>pre-build</td><td>  normal-top-level()</td><td>59.559578</td></tr>
<tr><td>org</td><td>failed</td><td>:pre-build command failed</td><td>59.565089</td></tr></tbody>
</table>
</details>

**Comment by progfolio** [comment] 2023-03-01 19:58
I was able to reproduce in a linux docker container for Emacs 28.2:

<details><summary>Log @2023-03-01 19:54:42 +0000</summary>
search filter: "^org$|"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>org</td><td>queued</td><td>Package queued</td><td>08.325394</td></tr>
<tr><td>org</td><td>cloning</td><td>Cloning</td><td>08.329046</td></tr>
<tr><td>org</td><td>cloning</td><td>Resolving deltas: 100% (15644/15644), done.</td><td>21.693648</td></tr>
<tr><td>org</td><td>pre-build</td><td>Running :pre-build commands</td><td>22.081923</td></tr>
<tr><td>org</td><td>pre-build</td><td>Running command: (progn (require 'elpaca-menu-org) (elpaca-menu-org--build))</td><td>22.172927</td></tr>
<tr><td>org</td><td>pre-build</td><td>Org version: 9.6.1 9.6.1-n/a-gaa2249</td><td>22.297246</td></tr>
<tr><td>org</td><td>pre-build</td><td>Loading /home/docker/.emacs.d/elpaca/repos/org/lisp/org-compat.el (source)...</td><td>22.346921</td></tr>
<tr><td>org</td><td>pre-build</td><td>Loading /home/docker/.emacs.d/elpaca/repos/org/mk/org-fixup.el (source)...</td><td>22.346946</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making loaddefs</td><td>22.346964</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making org-version</td><td>22.529727</td></tr>
<tr><td>org</td><td>pre-build</td><td>Making manuals</td><td>22.551747</td></tr>
<tr><td>org</td><td>pre-build</td><td>File mode specification error: (error Lisp nesting exceeds `max-lisp-eval-depth')</td><td>22.885750</td></tr>
<tr><td>org</td><td>pre-build</td><td>Debugger entered--Lisp error: (error "Lisp nesting exceeds `max-lisp-eval-depth'")</td><td>23.336560</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>23.336576</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336585</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336594</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>23.336601</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>23.336607</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>23.336615</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336623</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336631</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>23.336638</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>23.336645</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>23.336652</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336660</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336667</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>23.336674</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p(nil)</td><td>23.336681</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>23.336691</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336701</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336709</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>23.336716</td></tr>
<tr><td>org</td><td>pre-build</td><td>...</td><td>23.336723</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (if (derived-mode-p 'org-mode) (org-at-heading-p (not invisible-ok)) (apply oldfun invisible-ok extra))</td><td>23.336731</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p@fix-for-org-fold(#f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336741</td></tr>
<tr><td>org</td><td>pre-build</td><td>  apply(outline-on-heading-p@fix-for-org-fold #f(compiled-function (&optional invisible-ok) "Return t if point is on a (visible) heading line.\nIf INVISIBLE-OK is non-nil, an invisible heading line is ok too." #<bytecode 0x1a9e17dd0651058c>) t)</td><td>23.336749</td></tr>
<tr><td>org</td><td>pre-build</td><td>  outline-on-heading-p(t)</td><td>23.336755</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-at-heading-p()</td><td>23.336762</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-element-at-point()</td><td>23.336769</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-export-output-file-name(".texi" nil)</td><td>23.336776</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-texinfo-export-to-texinfo()</td><td>23.336783</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (while --dolist-tail-- (setq manual (car --dolist-tail--)) (find-file manual) (org-texinfo-export-to-texinfo) (setq --dolist-tail-- (cdr --dolist-tail--)))</td><td>23.336792</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (let ((--dolist-tail-- '("../doc/org-manual.org" "../doc/org-guide.org")) manual) (while --dolist-tail-- (setq manual (car --dolist-tail--)) (find-file manual) (org-texinfo-export-to-texinfo) (setq --dolist-tail-- (cdr --dolist-tail--))))</td><td>23.336800</td></tr>
<tr><td>org</td><td>pre-build</td><td>  org-make-manuals()</td><td>23.336808</td></tr>
<tr><td>org</td><td>pre-build</td><td>  elpaca-menu-org--build()</td><td>23.336816</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (progn (require 'elpaca-menu-org) (elpaca-menu-org--build))</td><td>23.336823</td></tr>
<tr><td>org</td><td>pre-build</td><td>  eval((progn (require 'elpaca-menu-org) (elpaca-menu-org--build)) t)</td><td>23.336830</td></tr>
<tr><td>org</td><td>pre-build</td><td>  elpaca--run-build-commands((progn (require 'elpaca-menu-org) (elpaca-menu-org--build)))</td><td>23.336837</td></tr>
<tr><td>org</td><td>pre-build</td><td>  (let ((load-prefer-newer t) (gc-cons-percentage 1.0)) (require 'elpaca) (normal-top-level-add-subdirs-to-load-path) (elpaca--run-build-commands '(progn (require 'elpaca-menu-org) (elpaca-menu-org--build))))</td><td>23.339206</td></tr>
<tr><td>org</td><td>pre-build</td><td>  eval((let ((load-prefer-newer t) (gc-cons-percentage 1.0)) (require 'elpaca) (normal-top-level-add-subdirs-to-load-path) (elpaca--run-build-commands '(progn (require 'elpaca-menu-org) (elpaca-menu-org--build)))) t)</td><td>23.339220</td></tr>
<tr><td>org</td><td>pre-build</td><td>  command-line-1(("-L" "./" "-L" "/home/docker/.emacs.d/elpaca/builds/elpaca/" "--eval" "(let ((load-prefer-newer t) (gc-cons-percentage 1...."))</td><td>23.339229</td></tr>
<tr><td>org</td><td>pre-build</td><td>  command-line()</td><td>23.339237</td></tr>
<tr><td>org</td><td>pre-build</td><td>  normal-top-level()</td><td>23.339244</td></tr>
<tr><td>org</td><td>failed</td><td>:pre-build command failed</td><td>23.340112</td></tr></tbody>
</table>
</details>

It looks like org-make-manuals is triggering an infinite loop somewhere along the line. I'll look to see if this is a known Org issue.

**Comment by progfolio** [comment] 2023-03-02 22:13
Sorry for the delay.
This should be fixed on the latest master branch.
You can test by ensuring the installer `:ref` value is `nil`, then:

1. `M-x elpaca-delete` `elpaca`
2. `M-x elpaca-delete` `org`
3. restarting Emacs

Testing is appreciated.

**Comment by sgtlaggy** [comment] 2023-03-03 00:19
Tested with my main config as well as `elpaca-test` again, both worked great!

**Closed** 2023-03-03 00:58 UTC
Labels: bug
