### ISSUE TITLE
[Bug]: elpaca ignores `external-completion` dependency of `eglot`

### ISSUE THREAD

**Issue by darkfeline** [progfolio/elpaca#168] opened 2023-07-31 00:37 UTC
### Elpaca Version

Elpaca daab805 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-02
git --version:  git version 2.41.0

### Operating System

Arch Linux

### Description

Basically, `external-completion` is a dependency of `eglot`, yet elpaca doesn't seem to be making `external-completion` available.  Explicitly doing `(elpaca external-completion)` works.

Tangential bug: `elpaca-test` seems to fail by losing the tmpdir if I don't pass `:keep t`.  Some sort of race?

<details open><summary>Test Case</summary>

```emacs-lisp
(elpaca-test :name "missing dep" :ref "master" :keep t :init
             (progn
               (elpaca eglot)
               (load "external-completion")))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>daab805 HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.5</td>
<tr><td>emacs</td><td>GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2023-01-02</td>
<tr><td>git</td><td>git version 2.41.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for elpaca-autoloads.el... 
  INFO     Scraping files for elpaca-autoloads.el...done
Cloning into '/tmp/elpaca.H3mqjE/elpaca/repos/elpaca'...
Already on 'master'
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.H3mqjE/elpaca/repos/elpaca...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/extensions/elpaca-use-package.el...

In toplevel form:
extensions/elpaca-use-package.el:28:1: Error: Cannot open load file: No such file or directory, use-package
Checking /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.H3mqjE/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 10 files compiled, 1 failed, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "external-completion")
  load("external-completion")
  load-with-code-conversion("/tmp/elpaca.H3mqjE/init.el" "/tmp/elpaca.H3mqjE/init.el" nil t)
  command-line-1(("--eval" "(setq debug-on-error t after-init-time nil)" "--eval" "(setq user-emacs-directory \"/tmp/elpaca.H3mqjE\")" "--eval" "(run-hooks 'before-init-hook)" "-l" "./init.el" "--eval" "(setq after-init-time (current-time))" "--eval" "(run-hooks 'after-init-hook)" "--eval" "(run-hooks 'emacs-startup-hook)" "--eval" "(message \"\n Test Env\n\")" "--eval" "(elpaca-version 'message)"))
  command-line()
  normal-top-level()

```
</details>

**Comment by progfolio** [comment] 2023-07-31 01:20
Thanks for taking the time to fill out a bug report.

> Basically, external-completion is a dependency of eglot, yet elpaca doesn't seem to be making external-completion available. Explicitly doing (elpaca external-completion) works.

Looks like the default value of `elpaca-ignored-dependencies` needed to be adjusted.
external-completion was only added in Emacs 29.
I've pushed a fix for that.


>  Tangential bug: elpaca-test seems to fail by losing the tmpdir if I don't pass :keep t. Some sort of race?

I'm unable to reproduce this on my end.  Could you please open a separate bug report with more info?
Try toggling debug-on-error and share a backtrace if possible.

**Comment by darkfeline** [comment] 2023-07-31 18:52
verified fix.  will look into test race later maybe

**Closed** 2023-07-31 19:08 UTC
Labels: bug
