### ISSUE TITLE
[Bug/Support]: fetch-all too many open files

### ISSUE THREAD

**Issue by sho-87** [progfolio/elpaca#258] opened 2024-02-13 07:31 UTC
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 11e96bf HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.2 (build 2, x86_64-w64-mingw32)
 of 2024-01-18
git --version:  git version 2.43.0.windows.1

### Operating System

Windows 11

### Description

Whenever I run `elpaca-fetch-all`, every fetch seems to fail for the same reason (num packages = 83):
```
vertico                        failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.862125
orderless                      failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.863146
consult                        failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.864130
marginalia                     failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.865222
dirvish                        failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.866220
dired-gitignore                failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.867193
centaur-tabs                   failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.868249
format-all                     failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.869133
avy                            failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.870043
lsp-mode                       failed               elpaca--fetch: (file-error "Creating pipe" "Too many open files")                14.870901
```
I've tried googling this, and seems to point to being an OS/emacs issue rather than elpaca specifically (a lot of answers I read were about OSX, however), but wondering if theres something that can be done on the elpaca side to mitigate this?

Things seem to work when I fetch individual packages, but this can be quite tedious as its hard to know if there are updates available for any given package ahead of time

**Comment by progfolio** [comment] 2024-02-13 11:32
Duplicate of https://github.com/progfolio/elpaca/issues/65.
Please see the `elpaca-queue-limit` user option.

**Closed by progfolio** 2024-02-13 11:32 UTC
