### ISSUE TITLE
[Bug]: Problem (re-)evaluating use-package declarations

### ISSUE THREAD

**Issue by deejayem** [progfolio/elpaca#133] opened 2023-05-24 11:16 UTC
### Elpaca Version

Elpaca 798351f HEAD -> master, origin/master, origin/HEAD
installer:      0.4
emacs-version:  GNU Emacs 28.2 (build 1, x86_64-apple-darwin22.4.0, Carbon Version 169 AppKit 2299.5)
git --version:  git version 2.40.1

### Operating System

MacOS Ventura 13.3

### Description

I switched from straight.el to elpaca, and most things seem to be working well (thank you!), but I appear to be having some issue (re-)evaluating use-package declarations after startup.

Here's a minimal config that reproduces it.

`early-init.el` is copied from your documentation/example, with the only non-comment, non-empty line being `(setq package-enable-at-startup nil)`

`init.el` is also copied from your documentation, with the only addition being `(use-package consult)`. Here is the full file:
```
;; Example Elpaca configuration -*- lexical-binding: t; -*-

(defvar elpaca-installer-version 0.4)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (kill-buffer buffer)
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (setq elpaca-use-package-by-default t))

(elpaca-wait)

(use-package consult)

;; Local Variables:
;; no-byte-compile: t
;; no-native-compile: t
;; no-update-autoloads: t
;; End:
```

So far, everything is fine. But now if I change `(use-package consult)` to the following:
```
(use-package consult
  :bind ("C-c r" . consult-ripgrep))
```
And then call either `eval-defun` or `eval-buffer` (or both!), `C-c r` is not bound (I get `C-c r is undefined`if I try to use it).

Then, if I also add `(use-package vertico)` and call `eval-defun`, vertico is not installed. However, if I call `eval-buffer`, `C-c r` is bound and vertico is installed. (If I just add vertico, without the consult change, `eval-buffer` doesn't install vertico).

If I start emacs with the `:bind` change for `consult-ripgrep`, `C-c r` works fine, regardless of if I've added vertico or not (and vertico is also installed fine if I add it before startup).

Before switching to elpaca, both `eval-defun` and `eval-buffer` worked fine for new or updated use-package delcarations, so I think something isn't working correctly here.

(In case it could have been part of the problem, my actual config is split into multiple files, so `eval-buffer` wasn't re-evaluating the elpaca setup code when I first encountered the issue).

**Comment by progfolio** [comment] 2023-05-25 03:27
Thanks for taking the time to fill out the bug report.
I've pushed a fix. As always, testing is appreciated.
You can update to the latest version of Elpaca by:

1. `M-x elpaca-update` `elpaca`
2. Restarting Emacs

**Comment by progfolio** [comment] 2023-05-25 21:56
> eval-defun does not work for new use-package declarations

Sorry, thought I had covered that case. I only had handled `eval-last-sexp`.
Pushed a patch to handle that.

I'm not sure about `eval-region` and `eval-buffer` yet.
They'll probably work in most cases, but each order which is evaluated would be immediately processed, ignoring the queue system.
I can think of a hacky way to work around this (add a debounce timer which is reset until the last evaluation takes place, then process the queue), but I'm not thrilled with that solution.

> Is there anything else I can do to help debug this?

Sure. I've pushed the debounce timer solution mentioned above to the "feat/elpaca-interactive-hack" branch.
Try playing around with that to see if it works OK for you when interactively evaluating `elpaca` forms with eval-region and eval-buffer. You can do that by evaluating the following test case in your \*scratch\* buffer:

```emacs-lisp
(elpaca-test
  :dir "elpaca.test"
  :ref "feat/elpaca-interactive-hack"
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  ;;Add whatever use-package forms you want to test here.
  )
```

It will launch a secondary Emacs session which will install Elpaca in a clean test environment. You can experiment there without touching your own config.

**Comment by deejayem** [comment] 2023-05-26 11:39
Thank you: `eval-defun` works on `master` now, and `eval-buffer` and `eval-region` work on `feat/elpaca-interactive-hack`.

This is beyond the scope of this issue, but it's slightly annoying to have an `*elpaca-log*` buffer popup everytime I re-evaluate something. Is there a way of preventing that? No problem if not.

**Comment by progfolio** [comment] 2023-05-27 14:06
David Morgan ***@***.***> writes:

> Thank you: eval-defun works on master now, and eval-buffer and 
> eval-region work on
> feat/elpaca-interactive-hack.

Thanks for testing. I've merged the eval-region/buffer support as 
well.
 
> This is beyond the scope of this issue, but it's slightly 
> annoying to have an *elpaca-log*
> buffer popup everytime I re-evaluate something. Is there a way 
> of preventing that? No
> problem if not.

Not quite yet, but it is planned.
There are a lot of different contexts which trigger logging.
I still have to think on how to efficiently handle that while 
allowing flexible customization.

**Closed** 2023-05-27 14:30 UTC
Labels: bug

**Comment by progfolio** [comment] 2023-07-02 14:59
> This is beyond the scope of this issue, but it's slightly annoying to have an *elpaca-log* buffer popup everytime I re-evaluate something. Is there a way of preventing that?

@deejayem: I've updated how the logging system works. You can now change when the log is displayed on a contextual basis. The default values should prevent the log from popping up in the case you describe above.
See https://github.com/progfolio/elpaca/wiki/Logging for some examples on how to configure the options.
Testing is appreciated. Thanks.

**Comment by deejayem** [comment] 2023-07-03 11:11
@progfolio it seems to be working well (with the default configuration) so far. I'll let you know if I run into any problems.

One very minor difference from straight, is that if I add `(use-package foo... )`, with straight I would see a message in the echo area if the package is being cloned. With elpaca I now don't get any indication that it's cloning a repository.

**Comment by progfolio** [comment] 2023-07-03 17:22
> @progfolio it seems to be working well (with the default configuration) so far, thank you. I'll let you know if I run into any problems.

Glad it's working. Thanks for testing.

> One very minor difference from straight, is that if I add `(use-package foo... )`, with straight I would see a message in the echo area if the package is being cloned. With elpaca I now don't get any indication that it's cloning a repository.

Straight doesn't have a concept of a log, so it uses messages. Elpaca's logging facilities are much more flexible and informative, but the trade off is that they would be too noisy to treat as regular messages. I think a nice balance for your personal preference would be something like the following:

- Use a minimal query when evaluating elpaca forms (or use-package forms when elpaca-use-package-mode is enabled).
     e.g. `#unique | !finished`
- Automatically close the log when it completes successfully. This should be doable via `elpaca-post-queue-hook`.
- Customize display-buffer-alist to display the log buffer where you want (e.g. keep it at the bottom and only N% or lines high)

If that sounds like something you're interested in, I could add an example to the wiki.

**Comment by deejayem** [comment] 2023-07-04 07:31
Yes, that sounds good - please add an example to the wiki.

**Comment by progfolio** [comment] 2023-07-06 00:09
> Yes, that sounds good - please add an example to the wiki.

I've added all the pieces to https://github.com/progfolio/elpaca/wiki/Logging
You'll want to the "Override silent commands", auto-hiding, and customizing the position bits. With all of that, you should only see the log window briefly pop-up when evaluating declarations. The log should auto-hide once the queue is finished processing.
Let me know how that works for you.

**Comment by deejayem** [comment] 2023-07-07 06:47
@progfolio thank you. Is there a way that we can distinguish between different scenarios for the auto-hiding? As what's in the wiki causes the buffer to be hidden after calling `elpaca-fetch-all`, which probably isn't what anyone wants.

**Comment by progfolio** [comment] 2023-07-07 14:45
> @progfolio thank you.

You're welcome.

> Is there a way that we can distinguish between different scenarios for the auto-hiding? As what's in the wiki causes the buffer to be hidden after calling `elpaca-fetch-all`, which probably isn't what anyone wants.

I've updated the example code in the wiki so that the hook function which hides the log checks a variable for the desired commands (defined above the hook function). Give that a shot.

**Comment by deejayem** [comment] 2023-07-11 13:49
> I've updated the example code in the wiki so that the hook function which hides the log checks a variable for the desired commands (defined above the hook function). Give that a shot.

I'm not sure that the combination works correctly. If I use both the overriding of silent commands and the auto-hiding, the `*elpaca-log*` buffer is opened, and does nto get hidden. (but without the overriding, I don't get the buffer).

Also, the code for overriding silent commands runs fine if I evaluate it once Emacs is running, but if I have it in my init, I get an error about `elpaca-log-command-queries` being undefined (I even tried moving that to `elpaca-after-init-hook`, but still got the same error), so I'm not sure at what point that can be run.

**Comment by progfolio** [comment] 2023-07-11 17:36
>  I have it in my init, I get an error about elpaca-log-command-queries being undefined

Wrapping the code which sets that variable in a `with-eval-after-load` should fix that.

> I'm not sure that the combination works correctly.

Please try evaluating the following test case in your \*scratch\* buffer.
Once everything has installed, try the following in the test Emacs session:

1. `M-x find-file` `init.el` (should be located at `/tmp/elpaca.log/init.el`).
2. Move point to the end of the `(elpaca doct)` declaration.
3. `M-x eval-last-sexp`

The log should auto hide after briefly popping up.
If it does not, please share the contents of the \*Messages\* buffer.

```emacs-lisp
(elpaca-test
  :dir "elpaca.log"
  :interactive t
  :early-init (setq elpaca-menu-functions nil)
  :init
  (elpaca (doct :host github :repo "progfolio/doct")
    (sit-for 0.2)) ;;artificial pause to ensure log is visible before hiding.
  (with-eval-after-load 'elpaca-log
    (setf (alist-get '(eval-buffer eval-region eval-defun eval-last-sexp org-ctrl-c-ctrl-c)
                     elpaca-log-command-queries nil nil #'equal)
          "#unique | !finished"))

  (defvar +elpaca-hide-log-commands '( eval-buffer eval-region eval-defun
                                       eval-last-sexp org-ctrl-c-ctrl-c)
    "List of commands for which a successfully processed log is auto hidden.")

  (defun +elpaca-hide-successful-log ()
    "Hide Elpaca log buffer if queues processed successfully."
    (message "this: %S last: %S" this-command last-command)
    (if-let ((incomplete (cl-find 'incomplete elpaca--queues :key #'elpaca-q<-status))
             ((elpaca-q<-elpacas incomplete)))
        nil
      (when-let ((log (bound-and-true-p elpaca-log-buffer))
                 (window (get-buffer-window log t)) ;; log buffer visible
                 ((or (member last-command +elpaca-hide-log-commands)
                      (member this-command +elpaca-hide-log-commands))))
        (with-selected-window window (quit-window 'kill window)))))
  (add-hook 'elpaca-post-queue-hook #'+elpaca-hide-successful-log)
  (add-to-list 'display-buffer-alist '("\\*elpaca-log\\*" (display-buffer-reuse-window display-buffer-at-bottom))))
```

**Comment by deejayem** [comment] 2023-07-12 06:40
> The log should auto hide after briefly popping up. If it does not, please share the contents of the *Messages* buffer.
> 

Yes, that works.

**Comment by progfolio** [comment] 2023-07-12 15:26
> > The log should auto hide after briefly popping up. If it does not, please share the contents of the _Messages_ buffer.
> 
> Yes, that works.

Thanks. I've updated the function in the wiki and will note that elpaca-log needs to be loaded prior to modifying `elpaca-log-command-queries`.

**Comment by deejayem** [comment] 2023-07-18 06:53
There's one scenario where it doesn't work (with the default settings, or the ones from the wiki). Sometimes I get errors when running `elpaca-fetch-all`:
![image](https://github.com/progfolio/elpaca/assets/2564003/6e6118b3-7acf-45af-9662-3a008be84fdb)
When this happens, the `*elpaca-log*` buffer pops up every time I evaluate a use-package form.

**Comment by progfolio** [comment] 2023-07-18 14:01
That's by design. The log is only hidden when successfully processed. Otherwise, you are meant to see that something failed.

> Sometimes I get errors when running elpaca-fetch-all

See: #156 for how to fix this.

**Comment by progfolio** [comment] 2023-07-18 14:50
Sounds good. If you come up with something you feel is worth sharing, feel free to add it to the wiki.
