### ISSUE TITLE
[Bug]: elpaca--date-version does not ignore user's git config

### ISSUE THREAD

**Issue by viriw** [progfolio/elpaca#256] opened 2024-02-11 12:02 UTC
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 325060c HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, cairo version 1.18.0)
 of 2024-02-08
git --version:  git version 2.43.0
```

### Operating System

Gentoo GNU/Linux amd64

### Description

Garbage issue title, not sure what to call this, sorry. Trying out elpaca again with a blank `user-init-file`. I try to install `magit`, ran into the `seq` issue, did the pinned workaround. These errors remain:

```
magit                          failed               Failed dependencies: (magit-section)                                             00.546592
magit-section                  failed               Requires dash minimum version: 20221013                                          00.550316
git-commit                     failed               Requires transient minimum version: 20231204                                     00.619223
```

According to `elpaca-info`, I have `dash` 2.19.1 13f3fcd and `transient` 0.5.3 85ecbc6 installed. Now I admit I don't yet write elisp packages and don't know how the development versioning works, but those commits are ahead of the calendar dates it's indicating, so I'm not sure what the complaint actually is.

**Comment by progfolio** [comment] 2024-02-11 17:13
Thanks for taking the time to fill out a ticket.
Please share the full text of the init file you are using.

**Comment by viriw** [comment] 2024-02-11 19:28
Sure, I've stripped it of personalisations to make it less confusing, and tested that it still happens.


<details open>
<summary>early-init-file</summary>

```elisp
;; -*- lexical-binding: t; no-byte-compile: t; -*-

(setq package-enable-at-startup nil)
```

</details>

<details open>
<summary>user-init-file</summary>

```elisp
;; -*- lexical-binding: t; no-byte-compile: t; -*-

(defvar elpaca-installer-version 0.6)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(defun +elpaca-unload-seq (e)
  (and (featurep 'seq) (unload-feature 'seq t))
  (elpaca--continue-build e))

(defun +elpaca-seq-build-steps ()
  (append (butlast (if (file-exists-p (expand-file-name "seq" elpaca-builds-directory))
                       elpaca--pre-built-steps elpaca-build-steps))
          (list '+elpaca-unload-seq 'elpaca--activate-package)))

(elpaca elpaca-use-package
  (elpaca-use-package-mode))

(elpaca-wait)

(elpaca `(seq :build ,(+elpaca-seq-build-steps)))
(use-package magit :ensure t)
```

</details>

Additionally, these, if they may be useful:

<details>
<summary>(elpaca-info 'dash)</summary>

```
dash [MELPA|GNU-devel ELPA]
A modern list library for Emacs

source: MELPA
url: https://github.com/magnars/dash.el
menu item recipe:
( :package "dash"
  :fetcher github
  :repo "magnars/dash.el"
  :files ("dash.el" "dash.texi")
  :source "MELPA")
full recipe:
( :package "dash"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :source "MELPA"
  :files ("dash.el" "dash.texi")
  :repo "magnars/dash.el"
  :fetcher github)
dependencies: 
  emacs >= 24
dependents: 
  magit
  magit-section
installed version: 2.19.1 13f9fcd
statuses:
  (finished activation info byte-compilation autoloads linking unblocked ref-checked-out cloning continued-dep queued)
files:
  $REPOS/dash/dash.texi → $BUILDS/dash/dash.texi
  $REPOS/dash/dash.el   → $BUILDS/dash/dash.el
log:
  [2024-02-11 13:19:01] Package queued
  [2024-02-11 13:19:02] Continued by: elpaca--continue-dependency
  [2024-02-11 13:19:02] Cloning
  [2024-02-11 13:19:02] $git clone --depth 1 https://github.com/magnars/dash.el.git /home/viri/.emacs.d/elpaca/repos/dash/
  [2024-02-11 13:19:02] Cloning into '/home/viri/.emacs.d/elpaca/repos/dash'...
  [2024-02-11 13:19:03] Resolving deltas: 100% (1/1), done.
  [2024-02-11 13:19:03] Continued by: elpaca--clone-process-sentinel
  [2024-02-11 13:19:03] Continued by: elpaca--configure-remotes
  [2024-02-11 13:19:03] Continued by: elpaca--checkout-ref
  [2024-02-11 13:19:03] Continued by: elpaca--dispatch-build-commands
  [2024-02-11 13:19:03] Continued by: elpaca--queue-dependencies
  [2024-02-11 13:19:03] No external dependencies
  [2024-02-11 13:19:03] Checking dependency versions
  [2024-02-11 13:19:03] Continued by: elpaca--check-version
  [2024-02-11 13:19:03] Linking build files
  [2024-02-11 13:19:03] Continued by: elpaca--link-build-files
  [2024-02-11 13:19:03] Build files linked
  [2024-02-11 13:19:03] Generating autoloads: /home/viri/.emacs.d/elpaca/builds/dash
  [2024-02-11 13:19:03] $/usr/bin/emacs -Q -L /home/viri/.emacs.d/elpaca/repos/elpaca/ -l /home/viri/.emacs.d/elpaca/repos/elpaca/elpaca.el --batch --eval (progn (setq gc-cons-percentage 1.0) (elpaca-generate-autoloads "dash" "/home/viri/.emacs.d/elpaca/builds/dash"))
  [2024-02-11 13:19:03]   INFO     Scraping files for loaddefs... 
  [2024-02-11 13:19:03]   INFO     Scraping files for loaddefs...done
  [2024-02-11 13:19:03]   GEN      dash-autoloads.el
  [2024-02-11 13:19:03] Continued by: #[128 "\302\301\303\300\"\"\207" [("Autoloads Generated" nil) elpaca--process-sentinel apply append] 6 "

(fn &rest ARGS2)"]
  [2024-02-11 13:19:03] Autoloads Generated
  [2024-02-11 13:19:03] Byte compiling
  [2024-02-11 13:19:03] $/usr/bin/emacs -q --batch --eval (let ((gc-cons-percentage 1.0) (native-comp-eln-load-path '("/home/viri/.emacs.d/eln-cache/" "/usr/lib64/emacs/29.1/native-lisp/"))) (dolist (dir '("/home/viri/.emacs.d/elpaca/builds/dash")) (let ((default-directory dir)) (add-to-list 'load-path dir) (normal-top-level-add-subdirs-to-load-path))) (byte-recompile-directory "/home/viri/.emacs.d/elpaca/builds/dash" 0 'force))
  [2024-02-11 13:19:03] Checking /home/viri/.emacs.d/elpaca/builds/dash...
  [2024-02-11 13:19:03] Compiling /home/viri/.emacs.d/elpaca/builds/dash/dash-autoloads.el...
  [2024-02-11 13:19:03] Compiling /home/viri/.emacs.d/elpaca/builds/dash/dash.el...
  [2024-02-11 13:19:04] Done (Total of 1 file compiled, 1 skipped)
  [2024-02-11 13:19:04] Continued by: #[128 "\302\301\303\300\"\"\207" [("Byte compilation complete" nil) elpaca--process-sentinel apply append] 6 "

(fn &rest ARGS2)"]
  [2024-02-11 13:19:04] Byte compilation complete
  [2024-02-11 13:19:04] Compiling Info files
  [2024-02-11 13:19:11] Continued by: elpaca--compile-info-process-sentinel
  [2024-02-11 13:19:11] Info compiled
  [2024-02-11 13:19:11] Installing Info files
  [2024-02-11 13:19:11] Continued by: elpaca--install-info
  [2024-02-11 13:19:11] /home/viri/.emacs.d/elpaca/builds/dash/dash.info
  [2024-02-11 13:19:11] Continued by: elpaca--install-info-process-sentinel
  [2024-02-11 13:19:11] Info installed
  [2024-02-11 13:19:11] Adding Info path
  [2024-02-11 13:19:11] Continued by: elpaca--add-info-path
  [2024-02-11 13:19:11] Continued by: elpaca--dispatch-build-commands
  [2024-02-11 13:19:11] Activating package
  [2024-02-11 13:19:11] Package build dir added to load-path
  [2024-02-11 13:19:11] Caching autoloads
  [2024-02-11 13:19:11] Autoloads cached
  [2024-02-11 13:19:11] Continued by: elpaca--activate-package
  [2024-02-11 13:19:11] ✓ 9.409 secs
```

</details>


<details>
<summary>(elpaca-info 'transient)</summary>

```
transient [MELPA|GNU-devel ELPA]
Transient commands

source: MELPA
url: https://github.com/magit/transient
menu item recipe:
( :package "transient"
  :fetcher github
  :repo "magit/transient"
  :files ("*.el" "*.el.in" "dir" "*.info"
	  "*.texi" "*.texinfo" "doc/dir"
	  "doc/*.info" "doc/*.texi"
	  "doc/*.texinfo" "lisp/*.el" (:exclude
				       ".dir-locals.el" "test.el" "tests.el"
				       "*-test.el" "*-tests.el" "LICENSE"
				       "README*" "*-pkg.el"))
  :source "MELPA")
full recipe:
( :package "transient"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :source "MELPA"
  :files (:defaults)
  :repo "magit/transient"
  :fetcher github)
dependencies: 
  emacs  >= 26.1
  compat >= 29.1.4.4
  seq    >= 2.24
dependents: 
  git-commit
  magit
installed version: 0.5.3 85ecbc6
statuses:
  (finished activation info byte-compilation autoloads linking unblocked blocked ref-checked-out cloning continued-dep queued)
files:
  $REPOS/transient/lisp/transient.el → $BUILDS/transient/transient.el
log:
  [2024-02-11 13:19:02] Package queued
  [2024-02-11 13:19:02] Continued by: elpaca--continue-dependency
  [2024-02-11 13:19:02] Cloning
  [2024-02-11 13:19:02] $git clone --depth 1 https://github.com/magit/transient.git /home/viri/.emacs.d/elpaca/repos/transient/
  [2024-02-11 13:19:02] Cloning into '/home/viri/.emacs.d/elpaca/repos/transient'...
  [2024-02-11 13:19:02] Resolving deltas: 100% (3/3), done.
  [2024-02-11 13:19:03] Continued by: elpaca--clone-process-sentinel
  [2024-02-11 13:19:03] Continued by: elpaca--configure-remotes
  [2024-02-11 13:19:03] Continued by: elpaca--checkout-ref
  [2024-02-11 13:19:03] Continued by: elpaca--dispatch-build-commands
  [2024-02-11 13:19:03] Queueing Dependencies
  [2024-02-11 13:19:03] Blocked by: (seq compat)
  [2024-02-11 13:19:04] Blocked by: (compat)
  [2024-02-11 13:19:10] Continued by: elpaca--check-status
  [2024-02-11 13:19:10] Unblocked by: compat
  [2024-02-11 13:19:10] Checking dependency versions
  [2024-02-11 13:19:10] Continued by: elpaca--check-version
  [2024-02-11 13:19:10] Linking build files
  [2024-02-11 13:19:10] Continued by: elpaca--link-build-files
  [2024-02-11 13:19:10] Build files linked
  [2024-02-11 13:19:10] Generating autoloads: /home/viri/.emacs.d/elpaca/builds/transient
  [2024-02-11 13:19:11] $/usr/bin/emacs -Q -L /home/viri/.emacs.d/elpaca/repos/elpaca/ -l /home/viri/.emacs.d/elpaca/repos/elpaca/elpaca.el --batch --eval (progn (setq gc-cons-percentage 1.0) (elpaca-generate-autoloads "transient" "/home/viri/.emacs.d/elpaca/builds/transient"))
  [2024-02-11 13:19:11]   INFO     Scraping files for loaddefs... 
  [2024-02-11 13:19:11]   INFO     Scraping files for loaddefs...done
  [2024-02-11 13:19:11]   GEN      transient-autoloads.el
  [2024-02-11 13:19:11] Continued by: #[128 "\302\301\303\300\"\"\207" [("Autoloads Generated" nil) elpaca--process-sentinel apply append] 6 "

(fn &rest ARGS2)"]
  [2024-02-11 13:19:11] Autoloads Generated
  [2024-02-11 13:19:11] Byte compiling
  [2024-02-11 13:19:11] $/usr/bin/emacs -q --batch --eval (let ((gc-cons-percentage 1.0) (native-comp-eln-load-path '("/home/viri/.emacs.d/eln-cache/" "/usr/lib64/emacs/29.1/native-lisp/"))) (dolist (dir '("/home/viri/.emacs.d/elpaca/builds/transient" "/home/viri/.emacs.d/elpaca/builds/compat" "/home/viri/.emacs.d/elpaca/builds/seq")) (let ((default-directory dir)) (add-to-list 'load-path dir) (normal-top-level-add-subdirs-to-load-path))) (byte-recompile-directory "/home/viri/.emacs.d/elpaca/builds/transient" 0 'force))
  [2024-02-11 13:19:11] Checking /home/viri/.emacs.d/elpaca/builds/transient...
  [2024-02-11 13:19:11] Compiling /home/viri/.emacs.d/elpaca/builds/transient/transient-autoloads.el...
  [2024-02-11 13:19:11] Compiling /home/viri/.emacs.d/elpaca/builds/transient/transient.el...
  [2024-02-11 13:19:12] Done (Total of 1 file compiled, 1 skipped)
  [2024-02-11 13:19:12] Continued by: #[128 "\302\301\303\300\"\"\207" [("Byte compilation complete" nil) elpaca--process-sentinel apply append] 6 "

(fn &rest ARGS2)"]
  [2024-02-11 13:19:12] Byte compilation complete
  [2024-02-11 13:19:12] Compiling Info files
  [2024-02-11 13:19:12] Continued by: elpaca--compile-info
  [2024-02-11 13:19:12] Info source files not found
  [2024-02-11 13:19:12] Continued by: elpaca--dispatch-build-commands
  [2024-02-11 13:19:12] Activating package
  [2024-02-11 13:19:12] Package build dir added to load-path
  [2024-02-11 13:19:12] Caching autoloads
  [2024-02-11 13:19:12] Autoloads cached
  [2024-02-11 13:19:12] Continued by: elpaca--activate-package
  [2024-02-11 13:19:12] ✓ 10.154 secs
```

</details>

**Comment by progfolio** [comment] 2024-02-11 20:21
I'm unable to reproduce the issue given the test you provided on Emacs 29.1 or Emacs 30.

> I've stripped it of personalisations to make it less confusing

The issue may be due to something in here, but it's hard to say without seeing any of it.

**Comment by viriw** [comment] 2024-02-11 20:42
I think you misunderstand, when I said

> I've stripped it of personalisations to make it less confusing, **and tested that it still happens**

I meant that I wiped my `user-emacs-directory`, put in that `early-init-file` and `user-init-file` that I also posted here, and still hit the same issue. I was trying to reduce it to not be related to something else, and I posted a version where I still encounter this problem. Just tried again to be sure with those exact contents and nothing else in my `user-emacs-directory` and I still get the exact same output.

**Comment by progfolio** [comment] 2024-02-11 20:52
Understood. Unfortunately I'm still not able to reproduce on my end. I'll see if there's another test case I can provide to get more info.

**Comment by progfolio** [comment] 2024-02-13 16:37
My hunch is that the heuristic for getting the date versioning for the packages is failing somehow. I've pushed a change to include the version being compared against in the error message. Would you mind testing from scratch again and sharing the failure messages from the elpaca-log buffer again?

**Comment by ryunix** [comment] 2024-02-14 01:56
How about adding `(elpaca-wait)` after ``(elpaca `(seq :build ,(+elpaca-seq-build-steps)))``?

**Comment by progfolio** [comment] 2024-02-14 03:20
> How about adding `(elpaca-wait)` after `` (elpaca `(seq :build ,(+elpaca-seq-build-steps))) ``?

That shouldn't effect the versions of the dependencies which are failing.

**Comment by ryunix** [comment] 2024-02-14 05:16
> That shouldn't effect the versions of the dependencies which are failing.

I'm sorry for the incorrect comment. :bow: 

I'm reporting that I couldn't reproduce the issue in my environment either.  I'm using Emacs 29.1 on Gentoo too.  The versions matched, except for the build date.

**Comment by viriw** [comment] 2024-02-14 07:35
Installed version `nil` is lower than `YYYYMMDD`, for both of them.

**Comment by progfolio** [comment] 2024-02-14 14:20
> Installed version nil is lower than YYYYMMDD, for both of them.

Thanks. That confirms my hunch.
We need to figure out why `elpaca--date-version` is not returning anything for those packages. A good first step would be to bypass the function altogether to see if the git command used is working. Let's use dash as our example.
Can you please:

1. Navigate to dash's repository directory (should be at `$ELPACA-DIR/repos/dash/`) in a shell.
2. Execute `git log -n 1 --format=%cd --date=format:%Y%m%d.%s`

What output do you get from that command?

**Comment by viriw** [comment] 2024-02-15 17:06
> ```(elpaca (` (seq :build (, (+elpaca-seq-build-steps)))))```

I imagine this part of the test is meant to be ```(elpaca `(seq :build ,(+elpaca-seq-build-steps)))``` like in my above `user-init-file`, otherwise that elisp gets a classic "wrong argument type: symbolp" et cetera, so I edited that part of the expression. Here are the results, and I did check to put `log.showSignature=true` in my `~/.gitconfig` beforehand;


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :ref "fix/date-version"
  :init (defun +elpaca-unload-seq (e)
	  (and (featurep 'seq) (unload-feature 'seq t))
	  (elpaca--continue-build e))
  (defun +elpaca-seq-build-steps ()
    (append (butlast (if
			 (file-exists-p
			  (expand-file-name "seq"
					    elpaca-builds-directory)) elpaca--pre-built-steps
		       elpaca-build-steps))
	    (list '+elpaca-unload-seq 'elpaca--activate-package)))
  (elpaca (` (seq :build (, (+elpaca-seq-build-steps)))))
  (elpaca magit)
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>00ce5bb HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>installer</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, cairo version 1.18.0) of 2024-02-08</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.rtJtUg/elpaca/repos/elpaca'...
Switched to a new branch 'fix/date-version'
branch 'fix/date-version' set up to track 'origin/fix/date-version'.
Checking /tmp/elpaca.rtJtUg/elpaca/repos/elpaca...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.rtJtUg/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...
elpaca-log: "#unique"
"
seq                            finished             ✓ 2.684 secs                                                                     13.568629
elpaca                         finished             ✓ 2.995 secs                                                                     13.876013
compat                         finished             ✓ 5.071 secs                                                                     17.447952
with-editor                    finished             ✓ 6.044 secs                                                                     18.308732
transient                      finished             ✓ 6.613 secs                                                                     19.018036
dash                           finished             ✓ 6.975 secs                                                                     19.279611
git-commit                     finished             ✓ 8.087 secs                                                                     20.342451
magit-section                  finished             ✓ 8.613 secs                                                                     20.923314
magit                          finished             ✓ 32.343 secs                                                                    43.224765
"

 Test Env

Elpaca 09a94ca HEAD -> fix/date-version, origin/fix/date-version
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, cairo version 1.18.0)
 of 2024-02-08
git --version:  git version 2.43.0
```
</details>

**Comment by progfolio** [comment] 2024-02-15 17:55
viri ***@***.***> writes:

>  (elpaca (` (seq :build (, (+elpaca-seq-build-steps)))))
>
> I imagine this part of the test is meant to be (elpaca `(seq 
> :build ,
> (+elpaca-seq-build-steps))) like in my above user-init-file, 
> otherwise that elisp gets a
> classic "wrong argument type: symbolp" et cetera, so I edited 
> that part of the expression.

Yes. That looks like it's an elisp pretty printer bug or 
limitation.
Thanks for pointing that out. I'll look into it.

> Here are the results, and I did check to put 
> log.showSignature=true in my ~/.gitconfig
> beforehand;
> elpaca-log: "#unique"
> "
> seq                            finished             ✓ 2.684 secs 
> 13.568629
> elpaca                         finished             ✓ 2.995 secs 
> 13.876013
> compat                         finished             ✓ 5.071 secs 
> 17.447952
> with-editor                    finished             ✓ 6.044 secs 
> 18.308732
> transient                      finished             ✓ 6.613 secs 
> 19.018036
> dash                           finished             ✓ 6.975 secs 
> 19.279611
> git-commit                     finished             ✓ 8.087 secs 
> 20.342451
> magit-section                  finished             ✓ 8.613 secs 
> 20.923314
> magit                          finished             ✓ 32.343 
> secs 
> 43.224765
> "
>
>  Test Env
>
> Elpaca 09a94ca HEAD -> fix/date-version, origin/fix/date-version
> installer:      0.6
> emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, 
> cairo version 1.18.0)
>  of 2024-02-08
> git --version:  git version 2.43.0

Looks like everything is working as expected.
I've merged the change into the master branch.
Thanks again for testing.

**Closed** 2024-02-15 17:58 UTC
Labels: bug
