### ISSUE TITLE
[Bug]: Updating packages won't always generate autoloads properly

### ISSUE THREAD

**Issue by Riyyi** [progfolio/elpaca#48] opened 2022-12-31 10:38 UTC
### Emacs Version

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

### Operating System

Arch Linux x86_64 on kernel 6.0.10-arch2-1

### Bug Description

Sometimes (not always) when I run `M-x elpaca-update-all` the autoloads will not get generated properly and I will be hit with void-function errors due to the packages no longer being loaded correctly. This also happens with the Elpaca package itself, which is annoying because then Emacs wont start loading the init at all. After updating and manually running `elpaca-rebuild` on the packages that broke will correctly produce autoloads.

Note: I did use chemacs2 when testing this, but I believe this doesnt affect the issue.

![2022-12-31-114148_maim](https://user-images.githubusercontent.com/1911807/210133815-2c919ecd-5e23-4bca-b0dc-fad0698ad646.png)

I've managed to capture this behavior in a minimal working example. Due to the nature of this odd behavior I have zipped up the before and after state of the entire `.emacs.d` directory when running the `elpaca-update-all` command.
[before.zip](https://github.com/progfolio/elpaca/files/10327179/before.zip) [after.zip](https://github.com/progfolio/elpaca/files/10327180/after.zip)

The contents of `elpaca-autoloads.el` after updating will look like the following below (there is a hex `0x000c` character on line 5 in the file which is not visually rendered):

### Relevant log output

```emacs-lisp
;;; elpaca-autoloads.el --- automatically extracted autoloads  -*- lexical-binding: t -*-
;;
;;; Code:


(provide 'elpaca-autoloads)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; elpaca-autoloads.el ends here
```

**Comment by progfolio** [comment] 2022-12-31 22:50
Thank you for the detailed report.

> I've managed to capture this behavior in a minimal working example. 

Could you please provide how you were able to trigger the behavior, step by step?
I have not been able to reproduce on my end so far by calling elpaca-update-all alone.

**Comment by Riyyi** [comment] 2023-01-01 00:21
All I did was
`\emacs --with-profile test`
`M-x elpaca-update-all`
Then I got the contents of the after.zip directory.

**Comment by progfolio** [comment] 2023-01-03 08:13
Unfortunately, I haven't been able to reproduce this on my end.
Your screenshot did reveal that the `elpaca-update` build steps were out of order.
I've corrected that in the latest version.
Let me know if this issue is crops up after updating Elpaca.
Thanks.

**Comment by progfolio** [comment] 2023-01-06 23:47
@Riyyi I've pushed a potential fix to the "fix/autoloads-28" branch.
Try it out when you get a chance and let me know if it works out OK for you.

**Comment by Riyyi** [comment] 2023-01-07 18:31
@progfolio I've switched to that branch. I'll try to update frequently and share my results here in a week or so.

**Comment by Riyyi** [comment] 2023-01-14 11:05
Updating has not caused any issues so far.

Im sure this is unrelated, but mentioning anyway. I changed the bootstrap lines
```emacs-lisp
;; :ref nil
:branch "fix/autoloads-28"
```
And the log Info says `fatal: Not possible to fast-forward, aborting.` for the elpaca package, but I verified the git branch is set to `fix/autoloads-28` in `/elpaca/repos/elpaca` and the other packages seemed to update fine.

**Comment by progfolio** [comment] 2023-01-14 16:24
Thanks for testing.

>  fatal: Not possible to fast-forward, aborting. for the elpaca package, 

This is because I've been rebasing the patch ontop of the latest master branch (rewriting git history).
So there's no way for git to automatically fast-forward when pulling in changes.

In general, if you see this error and have not  made personal changes to a package's source code,  you can safely `elpaca-delete` the package and then the most recent version will reinstall when Emacs is restarted. I have a plan for a feature to help explain and handle such cases, but I have not added it yet.

I've merged the fix into the master branch and deleted the patch branch. You'll  want to switch back to `:ref nil`.
Thanks again for testing.

**Closed by progfolio** 2023-01-14 16:24 UTC
Labels: bug
